// <auto-generated />
using AndonLights.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AndonLights.Migrations
{
    [DbContext(typeof(AndonLightsDbContext))]
    [Migration("20230611141109_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AndonLights.Model.AndonLight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<ZonedDateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("AndonLights", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 901,
                            CurrentState = "Green",
                            DateOfCreation = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856142000000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LastErrorMessage = "",
                            Name = "LampWithStats"
                        },
                        new
                        {
                            Id = 902,
                            CurrentState = "Green",
                            DateOfCreation = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856178000000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LastErrorMessage = "",
                            Name = "Seeded lamp1"
                        },
                        new
                        {
                            Id = 903,
                            CurrentState = "Green",
                            DateOfCreation = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856214000000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LastErrorMessage = "",
                            Name = "Seeded lamp2"
                        });
                });

            modelBuilder.Entity("AndonLights.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewApiKey")
                        .HasColumnType("text");

                    b.Property<bool>("NewKeyRequested")
                        .HasColumnType("boolean");

                    b.Property<ZonedDateTime>("OldKeyDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("AndonLights.Model.DailyStateStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ZonedDateTime>("DateOfStats")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MinutesSpentInState")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfEntries")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("DailyStateStats", (string)null);
                });

            modelBuilder.Entity("AndonLights.Model.MonthlyStateStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ZonedDateTime>("DateOfStats")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MinutesSpentInState")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberOfEntries")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("MonthlyStateStats", (string)null);
                });

            modelBuilder.Entity("AndonLights.Model.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<ZonedDateTime>("InTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LenghtOfSessionInMinutes")
                        .HasColumnType("double precision");

                    b.Property<ZonedDateTime>("OutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Sessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 901,
                            InTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856142000000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LenghtOfSessionInMinutes = 89.0,
                            OutTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856195400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            StateId = 901
                        },
                        new
                        {
                            Id = 902,
                            InTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856195400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LenghtOfSessionInMinutes = 840.0,
                            OutTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856699400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            StateId = 902
                        },
                        new
                        {
                            Id = 903,
                            InTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856699400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LenghtOfSessionInMinutes = 385.0,
                            OutTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856930400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            StateId = 901
                        },
                        new
                        {
                            Id = 904,
                            InTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16856930400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LenghtOfSessionInMinutes = 215.0,
                            OutTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16857059400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            StateId = 902
                        },
                        new
                        {
                            Id = 905,
                            InTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16857059400000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            LenghtOfSessionInMinutes = 121.0,
                            OutTime = new NodaTime.ZonedDateTime(NodaTime.Instant.FromUnixTimeTicks(16857132000000000L), NodaTime.TimeZones.TzdbDateTimeZoneSource.Default.ForId("UTC")),
                            StateId = 903
                        });
                });

            modelBuilder.Entity("AndonLights.Model.State", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("LightID")
                        .HasColumnType("integer");

                    b.Property<string>("StateColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("LightID");

                    b.ToTable("States", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 901,
                            LightID = 901,
                            StateColour = "Green"
                        },
                        new
                        {
                            ID = 902,
                            LightID = 901,
                            StateColour = "Yellow"
                        },
                        new
                        {
                            ID = 903,
                            LightID = 901,
                            StateColour = "Red"
                        },
                        new
                        {
                            ID = 904,
                            LightID = 902,
                            StateColour = "Green"
                        },
                        new
                        {
                            ID = 905,
                            LightID = 902,
                            StateColour = "Yellow"
                        },
                        new
                        {
                            ID = 906,
                            LightID = 902,
                            StateColour = "Red"
                        },
                        new
                        {
                            ID = 907,
                            LightID = 903,
                            StateColour = "Green"
                        },
                        new
                        {
                            ID = 908,
                            LightID = 903,
                            StateColour = "Yellow"
                        },
                        new
                        {
                            ID = 909,
                            LightID = 903,
                            StateColour = "Red"
                        });
                });

            modelBuilder.Entity("AndonLights.Model.DailyStateStats", b =>
                {
                    b.HasOne("AndonLights.Model.State", null)
                        .WithMany("DailyStats")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AndonLights.Model.MonthlyStateStats", b =>
                {
                    b.HasOne("AndonLights.Model.State", null)
                        .WithMany("MonthlyStats")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AndonLights.Model.Session", b =>
                {
                    b.HasOne("AndonLights.Model.State", null)
                        .WithMany("ClosedSessions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AndonLights.Model.State", b =>
                {
                    b.HasOne("AndonLights.Model.AndonLight", null)
                        .WithMany("States")
                        .HasForeignKey("LightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AndonLights.Model.AndonLight", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("AndonLights.Model.State", b =>
                {
                    b.Navigation("ClosedSessions");

                    b.Navigation("DailyStats");

                    b.Navigation("MonthlyStats");
                });
#pragma warning restore 612, 618
        }
    }
}
