version: "3.9"  
services:
  andon:
    image: andon
    container_name: andon_be
    ports:
      - "8080:80"
    depends_on:
      - sql
    
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    
      
