version:  '3.9'

services:
  andon:
    image: git.sztaki.hu:5050/zahoranl/andon-onlab
    container_name: andon_be
    ports:
      -  "80:80"
    depends_on:
      -  postgres
    environment:
      -  PGQL__HOST=postgres
      -  PGQL__PORT=5432
      -  PGQL__USER=postgres
      -  PGQL__PW=postgres
      -  PGQL__DB=ALDB
      
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      -  postgresvolume:/var/opt/postgres
    ports:
      -  "5432:5432"
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres
volumes:
  postgresvolume:
      